// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieWeb.Database;

namespace MovieWeb.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20200617132149_AddDataBack")]
    partial class AddDataBack
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieWeb.Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WatchStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WatchStatusId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieWeb.Domain.WatchStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WatchStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nog niet gezien"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Al gezien"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nooit meer zien!!!"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nog eens opnieuw zien"
                        });
                });

            modelBuilder.Entity("MovieWeb.Domain.Movie", b =>
                {
                    b.HasOne("MovieWeb.Domain.WatchStatus", "WatchStatus")
                        .WithMany()
                        .HasForeignKey("WatchStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
